trigger:
- main

pool:
  name: 'Projet2CLD'

steps:
# Étape 1 : Installer le SDK .NET
- task: UseDotNet@2
  displayName: 'Installer .NET SDK 8.x'
  inputs:
    packageType: 'sdk'
    version: '8.0.100'

# Étape 2 : Restaurer les dépendances
- script: |
    dotnet restore
  workingDirectory: './azure-functions'
  displayName: 'Restaurer les dépendances'

# Étape 2.1 : Lister les dépendances NuGet
- script: |
    dotnet list package
  workingDirectory: './azure-functions'
  displayName: 'Lister les dépendances NuGet'

# Étape 3 : Compiler le projet
- script: |
    dotnet build -c Release
  workingDirectory: './azure-functions'
  displayName: 'Compiler le projet'

# Étape 4 : Publier le projet
- script: |
    dotnet publish -c Release -o ./publishs
  workingDirectory: './azure-functions'
  displayName: 'Publier le projet'

# Étape 5 : Archiver le package
- task: ArchiveFiles@2
  displayName: 'Archiver les fichiers publiés'
  inputs:
    rootFolderOrFile: './azure-functions/publishs'  # Utiliser le même dossier que dans le publish
    archiveFile: '$(Build.ArtifactStagingDirectory)\\azure-functions.zip'
    archiveType: 'zip'

# Étape 6 : Publier l’artefact de build
- task: PublishBuildArtifacts@1
  displayName: 'Publier l’artefact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'FunctionApp'

