trigger:
- main

pool:
  name: 'Projet2CLD'

variables:
  ServiceBusConnectionString: ''

steps:
# Étape 1 : Déployer le Blob Storage
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Déployer le Blob Storage'
  inputs:
    azureResourceManagerConnection: 'AzureConnectionSub1'
    resourceGroupName: 'Projet-2'
    location: 'eastus'
    templateLocation: 'Linked artifact'
    csmFile: './infra/deploy-storage.json'
    csmParametersFile: './infra/parameters-storage.json'

# Étape 2 : Déployer le Service Bus
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Déployer le Service Bus'
  inputs:
    azureResourceManagerConnection: 'AzureConnectionSub1'
    resourceGroupName: 'Projet-2'
    location: 'eastus'
    templateLocation: 'Linked artifact'
    csmFile: './infra/deploy-servicebus.json'
    csmParametersFile: './infra/parameters-servicebus.json'

# Étape 3 : Récupérer la clé de connexion Service Bus
# On utilise scriptType: 'ps' (PowerShell) pour fonctionner correctement sur Windows.
- task: AzureCLI@2
  displayName: 'Récupérer la clé de connexion Service Bus'
  inputs:
    azureSubscription: 'AzureConnectionSub1'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $CONNECTION_STRING = az servicebus namespace authorization-rule keys list `
        --resource-group 'Projet-2' `
        --namespace-name 'AzureBus-TMEB' `
        --name 'RootManageSharedAccessKey' `
        --query 'primaryConnectionString' -o tsv
      Write-Host "##vso[task.setvariable variable=ServiceBusConnectionString]$CONNECTION_STRING"
  condition: succeeded()

# Étape 4 : Déployer la Function App en utilisant la clé récupérée
- task: AzureResourceManagerTemplateDeployment@3
  displayName: 'Déployer la Function App'
  inputs:
    azureResourceManagerConnection: 'AzureConnectionSub1'
    resourceGroupName: 'Projet-2'
    location: 'eastus'
    templateLocation: 'Linked artifact'
    csmFile: './infra/deploy-functionapp.json'
    csmParametersFile: './infra/parameters-functionapp.json'
    overrideParameters: >
      -serviceBusConnectionString "$(ServiceBusConnectionString)"

# Étape 5 : Vérifier le déploiement
- script: |
    echo "Clé Service Bus utilisée : $(ServiceBusConnectionString)"
    echo "Déploiement terminé avec succès."
  displayName: 'Vérification finale'
